//This file was automatically generated by LevelHelper 2
//based on the class template defined by the user.
//For more info please visit: http://www.gamedevhelper.com

#import "LHNodeProtocol.h"
#import "LHUserPropertyProtocol.h"

